export { BLACKBIRD_SCORING_READINESS_VERSION, classifyScoringKeyImpact, getSampleSufficiencyLabel, READINESS_SAMPLE_LIMITS, READINESS_SCORE_CAPS, READINESS_SCORE_WEIGHTS, READINESS_THRESHOLDS } from "@/lib/scoring/validation/constants";
export { buildCohortValidationSummaries, summarizeProviderComparisons } from "@/lib/scoring/validation/cohort-summary";
export { evaluateLeagueScoringReadiness } from "@/lib/scoring/validation/league-readiness";
export { evaluateOverallRecommendationReadiness } from "@/lib/scoring/validation/recommendations";
export { evaluateRowScoringReadiness, toRowValidationResult } from "@/lib/scoring/validation/row-readiness";
export { validateLeagueScoringSample } from "@/lib/scoring/validation/validate-sample";
export { buildDiscrepancyInvestigations, DISCREPANCY_THRESHOLDS } from "@/lib/scoring/validation/discrepancy";
export { extractExperimentCandidates, F4_EXPERIMENT_THRESHOLDS } from "@/lib/scoring/validation/experiment-candidates";
export type * from "@/lib/scoring/validation/types";
export type * from "@/lib/scoring/validation/live-evidence";
