import { buildHistoricalPlayerProfiles, writePlayerProfileArtifacts } from "@/lib/player-profiles";

import { loadLocalEnv } from "./h9-projection-hardening-utils";

loadLocalEnv();

const result = buildHistoricalPlayerProfiles();
const shardedManifest = writePlayerProfileArtifacts(result);

console.log("Blackbird Historical Player Profile Builder");
console.log(`  dry run: ${result.dryRun}`);
console.log(`  profiles built: ${result.diagnostics.totalProfilesBuilt}`);
console.log(`  profiles with weekly stats: ${result.diagnostics.profilesWithWeeklyStats}`);
console.log(`  profiles without weekly stats: ${result.diagnostics.profilesWithoutWeeklyStats}`);
console.log(`  profiles with multi-season stats: ${result.diagnostics.profilesWithMultiSeasonData ?? 0}`);
console.log(`  coverage labels: ${JSON.stringify(result.diagnostics.profilesByCoverageLabel ?? {})}`);
console.log(`  stat source: ${result.diagnostics.sourceFilesUsed?.playerStats ?? "unknown"}`);
console.log(`  roster source: ${result.diagnostics.sourceFilesUsed?.rosters ?? "unknown"}`);
console.log(`  seasons included: ${(result.diagnostics.seasonsIncluded ?? []).join(", ") || "none"}`);
console.log(`  min/max season: ${result.diagnostics.minSeason ?? "n/a"} / ${result.diagnostics.maxSeason ?? "n/a"}`);
console.log(`  artifact size bytes: ${result.diagnostics.artifactSizeBytes ?? "unknown"}`);
console.log(`  sharded manifest size bytes: ${shardedManifest.sizes.manifestSizeBytes}`);
console.log(`  sharded shard count: ${shardedManifest.shards.length}`);
console.log(`  largest shard size bytes: ${shardedManifest.sizes.largestShardSizeBytes}`);
console.log(`  average shard size bytes: ${shardedManifest.sizes.averageShardSizeBytes}`);
console.log(`  total sharded size bytes: ${shardedManifest.sizes.totalShardedSizeBytes}`);
console.log(`  profiles with IDP stats: ${result.diagnostics.profilesWithIdpStats}`);
console.log(`  profiles with warnings: ${result.diagnostics.profilesWithWarnings}`);
console.log(`  profiles with usage summary: ${result.diagnostics.profilesWithUsageSummary ?? 0}`);
console.log(`  profiles with offensive usage: ${result.diagnostics.profilesWithOffensiveUsage ?? 0}`);
console.log(`  profiles with IDP usage: ${result.diagnostics.profilesWithIdpUsage ?? 0}`);
console.log(`  profiles with snap data: ${result.diagnostics.profilesWithSnapData ?? 0}`);
console.log(`  profiles missing snap data: ${result.diagnostics.profilesMissingSnapData ?? 0}`);
console.log(`  profiles with high-value usage: ${result.diagnostics.profilesWithHighValueUsage ?? 0}`);
console.log(`  profiles with red-zone usage: ${result.diagnostics.profilesWithRedZoneUsage ?? 0}`);
console.log(`  profiles with end-zone targets: ${result.diagnostics.profilesWithEndZoneTargets ?? 0}`);
console.log(`  profiles with goal-line carries: ${result.diagnostics.profilesWithGoalLineCarries ?? 0}`);
console.log(`  profiles with deep targets: ${result.diagnostics.profilesWithDeepTargets ?? 0}`);
console.log(`  profiles with role label: ${result.diagnostics.profilesWithRoleLabel ?? 0}`);
console.log(`  usage sources used: ${(result.diagnostics.usageSourceFiles?.used ?? []).join(", ") || "none"}`);
console.log(`  usage sources missing: ${(result.diagnostics.usageSourceFiles?.missing ?? []).join(", ") || "none"}`);
console.log(`  snap rows loaded: ${result.diagnostics.usageSourceFiles?.snapCounts?.rowCount ?? 0}`);
console.log(`  snap seasons detected: ${(result.diagnostics.usageSourceFiles?.snapCounts?.seasons ?? []).join(", ") || "none"}`);
console.log(`  snap rows matched/unmatched: ${result.diagnostics.usageSourceFiles?.snapCounts?.matchedRows ?? 0} / ${result.diagnostics.usageSourceFiles?.snapCounts?.unmatchedRows ?? 0}`);
console.log(`  participation rows loaded: ${result.diagnostics.usageSourceFiles?.participation?.rowCount ?? 0}`);
console.log(`  participation seasons detected: ${(result.diagnostics.usageSourceFiles?.participation?.seasons ?? []).join(", ") || "none"}`);
console.log(`  participation rows matched/unmatched: ${result.diagnostics.usageSourceFiles?.participation?.matchedRows ?? 0} / ${result.diagnostics.usageSourceFiles?.participation?.unmatchedRows ?? 0}`);
console.log(`  play-by-play source: ${result.diagnostics.usageSourceFiles?.pbp?.exists ? "found" : "missing"}`);
console.log(`  play-by-play selected file: ${result.diagnostics.usageSourceFiles?.pbp?.selectedFile ?? "none"}`);
console.log(`  play-by-play candidates checked: ${(result.diagnostics.usageSourceFiles?.pbp?.candidateFiles ?? []).join(", ") || "none"}`);
console.log(`  play-by-play rows loaded: ${result.diagnostics.usageSourceFiles?.pbp?.rowCount ?? 0}`);
console.log(`  play-by-play seasons detected: ${(result.diagnostics.usageSourceFiles?.pbp?.seasons ?? []).join(", ") || "none"}`);
console.log(`  play-by-play missing columns: ${(result.diagnostics.usageSourceFiles?.pbp?.missingColumns ?? []).join(", ") || "none"}`);
console.log(`  play-by-play derived player-weeks: ${result.diagnostics.usageSourceFiles?.pbp?.derivedPlayerWeekRows ?? 0}`);
console.log(`  play-by-play rows matched/unmatched: ${result.diagnostics.usageSourceFiles?.pbp?.matchedRows ?? 0} / ${result.diagnostics.usageSourceFiles?.pbp?.unmatchedRows ?? 0}`);
console.log(`  profiles by position: ${JSON.stringify(result.diagnostics.profilesByPosition)}`);
console.log(`  profiles by match confidence: ${JSON.stringify(result.diagnostics.profilesByMatchConfidence)}`);
console.log(`  scoring profile: ${result.scoringProfile.label} (${result.scoringProfile.version})`);
console.log("  artifacts:");
console.log("    artifacts/projections/player-profiles.json");
console.log("    artifacts/projections/player-profiles-summary.md");
console.log("    artifacts/projections/player-profiles-sample.md");
console.log("    artifacts/projections/player-profiles-diagnostics.json");
console.log("    artifacts/projections/player-profiles-shards-diagnostics.json");
console.log("    artifacts/projections/player-profiles-sharded/manifest.json");
console.log("    artifacts/projections/player-profiles-sharded/shards/");
